- name: Install base packages on new servers Corporation of WNTN
  hosts: all
  tasks:
    - name: Install base packages
      block:
      - name: Install nginx
        apt:
          name: nginx
          state: latest
          update_cache: true
    - name: Start and enable services
      block:
      - name: S/E nginx
        ansible.builtin.systemd:
          name: nginx
          state: started
          enabled: true
